name: Integration Test
on:
  workflow_call:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
        type: string
      context-ref:
        description: "Context in which the workflow runs. If the pull request is from a fork, this is the pull request target branch. Otherwise, this is the pull request branch so committers can test workflow changes directly."
        required: true
        type: string
      SHA:
        description: "SHA under test (head of the pull request branch)."
        required: true
        type: string
      base-SHA:
        description: "SHA of the base branch (target branch of the pull request)."
        required: true
        type: string
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
        type: string
      context-ref:
        description: "Context in which the workflow runs. If the pull request is from a fork, this is the pull request target branch. Otherwise, this is the pull request branch so committers can test workflow changes directly."
        required: true
        type: string
      SHA:
        description: "SHA under test (head of the pull request branch)."
        required: true
        type: string
      base-SHA:
        description: "SHA of the base branch (target branch of the pull request)."
        required: true
        type: string
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Set initial commit status
        uses: cilium/tetragon/.github/actions/set-commit-status@main
        with:
          sha: ${{ inputs.SHA || github.sha }}
          context: Integration Test

  build:
    needs: commit-status-start
    runs-on: ubuntu-24.04
    timeout-minutes: 40
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: ${{ inputs.SHA || github.sha }}
        persist-credentials: false

    - name: Set Up Job Variables
      id: vars
      env:
        SHA: ${{ inputs.SHA || github.sha }}
      run: |
        echo "operatorImage=quay.io/cilium/tetragon-operator-ci:${SHA}" >> $GITHUB_OUTPUT

    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.26.6'

    - name: Create a Kind cluster
      run: |
        make kind

    - name: Pull Tetragon Images
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
      with:
        timeout_minutes: 2
        max_attempts: 30
        retry_wait_seconds: 30
        warning_on_retry: false
        command: |
          set -e
          docker pull ${{ steps.vars.outputs.operatorImage }}

    - name: Run go tests
      run: |
        helm upgrade --install tetragon ./install/kubernetes/tetragon -n kube-system \
          --set tetragonOperator.podInfo.enabled=true \
          --set tetragonOperator.image.override=${{ steps.vars.outputs.operatorImage }}
        kubectl rollout status -n kube-system deployment/tetragon-operator
        go test --tags=integration -v ./operator/... ./pkg/manager/... ./pkg/sensors/exec/procevents/... ./pkg/watcher/crdwatcher/...

  merge-upload-and-status:
    name: Merge Upload and Status
    if: ${{ always() }}
    needs:
      - build
    permissions:
      actions: read
      contents: read
      statuses: write
    uses: ./.github/workflows/common-post-jobs.yml
    with:
      context-ref: ${{ inputs.context-ref || github.sha }}
      sha: ${{ inputs.SHA || github.sha }}
      success: ${{ needs.build.result == 'success' }}
      status-context: Integration Test